[project]
name = "llm-from-scratch"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "numpy>=2.2.2",
    "torch==2.4.0",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "uv>=0.5.26",
]
